### PR TITLE
CI: use update_release instead of release_suffix

### PR DESCRIPTION
**Pull request by jpopelka**
[update_release](https://packit.dev/docs/configuration/#update_release) is a new way how to tell Packit to not update the release string

### CODE REVIEW

**Review by lzaoral — APPROVED** [review]
LGTM! Thanks @jpopelka!

**Comment by kdudka** [comment]
Thank you both!  Merging...

**Comment by lzaoral** [comment]
Note that the same change must be done to other projects in the @csutils namespace and @kdudka/predator as well.

**Comment by jpopelka** [comment]
> same change must be done to other projects

I'll leave that up to you ;-)
This was just to let you know that there is this new option.

**Pull request merged**
