### PR TITLE
csgrep --imp-level=1: filter out important defects

### PR DESCRIPTION
**Pull request by kdudka**
Related: https://issues.redhat.com/browse/OSH-289

### CODE REVIEW

**Comment by jperezdealgaba** [comment]
Hey @kdudka! I looked at the code and I didn't find any major issues. Nevertheless, I may not be the perfect candidate to do code review for C. I also added @hanchuntao as a reviewer

**Comment by kdudka** [comment]
Thanks!  I should have written that the only significant change is the commit 356904a3f3c7701e71a40718d50e1446bbab4181.  The other two commits are just moving code around.

**Review by jamacku — APPROVED** [review]
LGTM :+1:

**Comment by kdudka** [comment]
@jamacku Thanks for review!

**Pull request merged**
