### PR TITLE
csparser: do not reject <Unknown> produced by symbiotic2cs

### PR DESCRIPTION
**Pull request by kdudka**
Fixes: https://github.com/csutils/csdiff/issues/37
Closes: https://github.com/csutils/csdiff/pull/38

### CODE REVIEW

**Comment by lzaoral** [comment]
I suggest dropping this PR in favour of https://github.com/aufover/rpm-symbiotic/pull/6 so that the format stays consistent across all of our output converters.

**Comment by kdudka** [comment]
The proposed change is a no-op if the input is correct.  On the other hand, I see no benefit in rejecting `<Unknown>`.  It would only complicate processing of results obtained by an old version of `symbiotc2cs`.  So I would prefer to merge both the pull requests.

**Comment by lzaoral** [comment]
Alright. Merging,

**Comment by kdudka** [comment]
Thanks!

**Pull request merged**
