### PR TITLE
writer-sarif: add descriptions for ShellCheck rules

### PR DESCRIPTION
**Pull request by lzaoral**

### CODE REVIEW

**Review by jamacku — APPROVED** [review]
<p>
  LGTM, This is great! Thank you @lzaoral
  
  
  
  
</p>

tested in - https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/371

Screenshot from 2024-04-17 12-50-50

EDIT:

For reference, this is the behavior before this PR

Screenshot from 2024-04-17 13-36-50

**Comment by kdudka** [comment]
@jamacku  I cannot see the `Show more details` link and the buttons at https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/371.  Do I need to be in a specific role on the project to see them?

**Comment by jamacku** [comment]
@kdudka Yes, you have to have access to the Security dashboard of the project in order to see those links. I think you need at lease write access to the repo.

**Review by kdudka — APPROVED** [review]
This indeed improves the way how GitHub renders the findings.

**Pull request merged**
